#version: '3.1'
#
#services:
#  calcio-app:
#    build: .
#    container_name: calcio-app
#    ports:
#      - 8081:8080
#    depends_on:
#      - calcio-db
#    links:
#      - calcio-db
#
#  calcio-db:
#    image: mariadb
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: admin
#      MYSQL_USER: admin
#      MYSQL_PASSWORD: admin
#      MYSQL_DATABASE: calcio-db
#    ports:
#      - 3316:3306

version: '3.1'
services:
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: calcio_db
    ports:
      - 3316:3306
  backend:
    depends_on:
      - database
    build: .
    restart: always
    command: java -jar /app.jar --spring.datasource.url="jdbc:mariadb://database/calcio_db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false" --spring.datasource.password="admin"
    ports:
      - 8081:8080
