spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    show-sql: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3316/calcio_db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: admin

springdoc:
  api-docs:
    path: /api-docs