#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect
#        enable_lazy_load_no_trans: true
#    open-in-view: false
#    show-sql: true
#
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://calcio-db:3306/calcio-db
#    username: root
#    password: admin
#
#springdoc:
#  api-docs:
#    path: /api-docs